<div id="connection-error" class="hide alert alert-error">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong>Warning!</strong> Unable to connect, please <a href="<?php echo $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] ?>">refresh</a> to try again.
</div>

<div id="activity-stream">

<?php if (0 === count($params['activities'])) : ?>

  <p id="no-activities"><?php echo get_option('no-activities-message', 'Sorry there are currently no activities, please check back another time.'); ?></p>

<?php else : ?>

  <?php foreach ($params['activities'] as $activity) : ?>
    
      <?php
    
      $activityData = json_decode($activity->data);
    
      if($activityData === NULL) {
        // Do nothing as json not properly formed / error parsing json
        continue;
      }
    
      $activityTemplate = file_get_contents(__DIR__.'/activity.phtml');
      echo $templateEngine->render($activityTemplate, $activityData);         
    
      ?>
  
  <?php endforeach ?>

<?php endif ?>
    
</div>